//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HandyCrab.UI {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HandyCrab.UI.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Diese App ist im Rahmen einer Prüfungsleistung an der DHBW Stuttgart Campus Horb entstanden. Der Quellcode ist unter folgender URL verfügbar. ähnelt.
        /// </summary>
        internal static string AboutPageContentText {
            get {
                return ResourceManager.GetString("AboutPageContentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Über ähnelt.
        /// </summary>
        internal static string AboutPageTitle {
            get {
                return ResourceManager.GetString("AboutPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Barriere hinzufügen ähnelt.
        /// </summary>
        internal static string AddBarrier {
            get {
                return ResourceManager.GetString("AddBarrier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hinzugefügt von:  ähnelt.
        /// </summary>
        internal static string AddedBy {
            get {
                return ResourceManager.GetString("AddedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lösung hinzufügen ähnelt.
        /// </summary>
        internal static string AddSolution {
            get {
                return ResourceManager.GetString("AddSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Beschreibung ähnelt.
        /// </summary>
        internal static string BarrierDescriptionPlaceholder {
            get {
                return ResourceManager.GetString("BarrierDescriptionPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lösung (optional) ähnelt.
        /// </summary>
        internal static string BarrierInitialSolutionPlaceholder {
            get {
                return ResourceManager.GetString("BarrierInitialSolutionPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Titel ähnelt.
        /// </summary>
        internal static string BarrierTitlePlaceholder {
            get {
                return ResourceManager.GetString("BarrierTitlePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Abbruch ähnelt.
        /// </summary>
        internal static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Suchposition anpassen ähnelt.
        /// </summary>
        internal static string ChangeLocationButtonText {
            get {
                return ResourceManager.GetString("ChangeLocationButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bild auswählen ähnelt.
        /// </summary>
        internal static string ChoosePictureButtonText {
            get {
                return ResourceManager.GetString("ChoosePictureButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stadt:  ähnelt.
        /// </summary>
        internal static string CityLabel {
            get {
                return ResourceManager.GetString("CityLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bestätigen ähnelt.
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Aktuelle Position ähnelt.
        /// </summary>
        internal static string CurrentPosition {
            get {
                return ResourceManager.GetString("CurrentPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Löschen ähnelt.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Distanz:  ähnelt.
        /// </summary>
        internal static string Distance {
            get {
                return ResourceManager.GetString("Distance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bearbeiten ähnelt.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die E-Mail oder Benutzername ähnelt.
        /// </summary>
        internal static string EmailOrUsernamePlaceholder {
            get {
                return ResourceManager.GetString("EmailOrUsernamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die E-Mail ähnelt.
        /// </summary>
        internal static string EmailPlaceholder {
            get {
                return ResourceManager.GetString("EmailPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fehler ähnelt.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die Barriere konnte nicht gefunden werden. ähnelt.
        /// </summary>
        internal static string Error_BarrierNotFound {
            get {
                return ResourceManager.GetString("Error_BarrierNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dies ist keine gültige E-Mail Adresse. ähnelt.
        /// </summary>
        internal static string Error_InvalidMail {
            get {
                return ResourceManager.GetString("Error_InvalidMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dies ist kein gültiges Passwort. ähnelt.
        /// </summary>
        internal static string Error_InvalidPassword {
            get {
                return ResourceManager.GetString("Error_InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Das Format des ausgewählten Bildes wird nicht unterstützt. Bitte wählen sie ein anderes. ähnelt.
        /// </summary>
        internal static string Error_InvalidPictureFormat {
            get {
                return ResourceManager.GetString("Error_InvalidPictureFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dies ist keine gültige Postleitzahl ähnelt.
        /// </summary>
        internal static string Error_InvalidPostcode {
            get {
                return ResourceManager.GetString("Error_InvalidPostcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dies ist kein gültiger Benutzername. ähnelt.
        /// </summary>
        internal static string Error_InvalidUsername {
            get {
                return ResourceManager.GetString("Error_InvalidUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Diese E-Mail Adresse wird bereits verwendet. ähnelt.
        /// </summary>
        internal static string Error_MailAlreadyInUse {
            get {
                return ResourceManager.GetString("Error_MailAlreadyInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die App konnte keine Verbindung zum Server aufbauen. Bitte stellen Sie sicher, dass eine Internetverbindung besteht. ähnelt.
        /// </summary>
        internal static string Error_NetworkTimeout {
            get {
                return ResourceManager.GetString("Error_NetworkTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sie sind nicht eingeloggt ähnelt.
        /// </summary>
        internal static string Error_NotLoggedIn {
            get {
                return ResourceManager.GetString("Error_NotLoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Das ausgewählte Bild ist zu groß. Bitte wählen Sie ein kleineres. ähnelt.
        /// </summary>
        internal static string Error_PictureTooBig {
            get {
                return ResourceManager.GetString("Error_PictureTooBig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die Lösung konnte nicht gefunden werden. ähnelt.
        /// </summary>
        internal static string Error_SolutionNotFound {
            get {
                return ResourceManager.GetString("Error_SolutionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unbekannter Fehler:  ähnelt.
        /// </summary>
        internal static string Error_UnknownError {
            get {
                return ResourceManager.GetString("Error_UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dieser Benutzername wird bereits verwendet. ähnelt.
        /// </summary>
        internal static string Error_UsernameAlreadyInUse {
            get {
                return ResourceManager.GetString("Error_UsernameAlreadyInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Der Benutzername oder das Passwort ist falsch. ähnelt.
        /// </summary>
        internal static string Error_WrongLogin {
            get {
                return ResourceManager.GetString("Error_WrongLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Github Projekt ähnelt.
        /// </summary>
        internal static string GitHubButtonLabel {
            get {
                return ResourceManager.GetString("GitHubButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die https://github.com/N-Olbert/HandyCrab_Xamarin ähnelt.
        /// </summary>
        internal static string GitHubProjectLink {
            get {
                return ResourceManager.GetString("GitHubProjectLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Breitengrad:  ähnelt.
        /// </summary>
        internal static string LatitudeLabel {
            get {
                return ResourceManager.GetString("LatitudeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Suchposition: ähnelt.
        /// </summary>
        internal static string LocationToSearchLabel {
            get {
                return ResourceManager.GetString("LocationToSearchLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Login ähnelt.
        /// </summary>
        internal static string LoginButtonText {
            get {
                return ResourceManager.GetString("LoginButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ausloggen ähnelt.
        /// </summary>
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Längengrad:  ähnelt.
        /// </summary>
        internal static string LongitudeLabel {
            get {
                return ResourceManager.GetString("LongitudeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ich habe noch keinen Account ähnelt.
        /// </summary>
        internal static string NoAccountButtonText {
            get {
                return ResourceManager.GetString("NoAccountButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die OK ähnelt.
        /// </summary>
        internal static string OkButton {
            get {
                return ResourceManager.GetString("OkButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Passwort ähnelt.
        /// </summary>
        internal static string PasswordPlaceholder {
            get {
                return ResourceManager.GetString("PasswordPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Suchmodus auswählen ähnelt.
        /// </summary>
        internal static string PickSearchMode {
            get {
                return ResourceManager.GetString("PickSearchMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Suchradius auswählen ähnelt.
        /// </summary>
        internal static string PickSearchRadius {
            get {
                return ResourceManager.GetString("PickSearchRadius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Postleitzahl ähnelt.
        /// </summary>
        internal static string Postcode {
            get {
                return ResourceManager.GetString("Postcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PLZ:  ähnelt.
        /// </summary>
        internal static string PostcodeLabel {
            get {
                return ResourceManager.GetString("PostcodeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Änderungen speichern ähnelt.
        /// </summary>
        internal static string SaveChanges {
            get {
                return ResourceManager.GetString("SaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Suchen ähnelt.
        /// </summary>
        internal static string SearchButtonText {
            get {
                return ResourceManager.GetString("SearchButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Suchmodus ähnelt.
        /// </summary>
        internal static string SearchMode {
            get {
                return ResourceManager.GetString("SearchMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Suchradius ähnelt.
        /// </summary>
        internal static string SearchRadiusPickerTitle {
            get {
                return ResourceManager.GetString("SearchRadiusPickerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Registrieren ähnelt.
        /// </summary>
        internal static string SignUpButtonText {
            get {
                return ResourceManager.GetString("SignUpButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sortierkriterium:  ähnelt.
        /// </summary>
        internal static string SortMode {
            get {
                return ResourceManager.GetString("SortMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sortierkriterium ähnelt.
        /// </summary>
        internal static string SortModePickerTitle {
            get {
                return ResourceManager.GetString("SortModePickerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Straße:  ähnelt.
        /// </summary>
        internal static string StreetLabel {
            get {
                return ResourceManager.GetString("StreetLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zum Aktualisieren der Position von oben nach unten ziehen ähnelt.
        /// </summary>
        internal static string SwipeToUpdatePosition {
            get {
                return ResourceManager.GetString("SwipeToUpdatePosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bild aufnehmen ähnelt.
        /// </summary>
        internal static string TakePictureButtonText {
            get {
                return ResourceManager.GetString("TakePictureButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Benutzername ähnelt.
        /// </summary>
        internal static string UsernamePlaceHolder {
            get {
                return ResourceManager.GetString("UsernamePlaceHolder", resourceCulture);
            }
        }
    }
}
